---
# tasks file for guacamole-ansible-role

- name: Check if guacamole server is installed
  stat:
    path: /usr/local/sbin/guacd
  register: server_is_installed

- name: Create temp server directory
  file:
    path: '{{ guacamole_temp_path }}/server'
    state: directory
    mode: '0755'

- name: Download Guacamole Server
  get_url:
    url: http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/{{ guacamole_version }}/source/guacamole-server-{{ guacamole_version }}.tar.gz
    dest: '{{ guacamole_temp_path }}/server'
  when: server_is_installed.stat.exists == False

- name: Extract guacamole server
  unarchive:
    src: '{{ guacamole_temp_path }}/server/guacamole-server-{{ guacamole_version }}.tar.gz'
    dest: '{{ guacamole_temp_path }}/server/'
    remote_src: yes
  when: server_is_installed.stat.exists == False


- name: Build from source and install guacamole server (1/2)
  shell: '{{ item }}'
  args:
    chdir: '{{ guacamole_temp_path }}/server/guacamole-server-{{ guacamole_version }}'
    creates: /usr/local/sbin/guacd
  register: server_installed
  with_items: ["./configure --with-init-dir=/etc/init.d", "make", "make install" ]
  when: server_is_installed.stat.exists == False

- name: Build from source and install guacamole server (2/2)
  shell: ldconfig
  args:
    chdir: '{{ guacamole_temp_path }}/server'
  when: server_installed is changed
