---
# tasks file for guacamole-ansible-role

- name: Configure guacamole
  template:
    src: guacamole.properties.j2 
    dest: /etc/guacamole/guacamole.properties
  notify: restart tomcat

- name: Configure guacd
  template:
    src: guacd.conf.j2
    dest: /etc/guacamole/guacd.conf
  notify: restart guacd
