---
# tasks file for guacamole-ansible-role

- name: Remove anonymous users
  mysql_user:
    login_user: root
    login_password: '{{ guacamole_mysql_root_password }}'
    name: ''
    login_host: "localhost"
    state: absent

- name: Remove root remote access 
  mysql_user:
    login_user: root
    login_password: '{{ guacamole_mysql_root_password }}'
    user: "root"
    host: "localhost"

- name: Remove test database
  mysql_db:
    login_user: root
    login_password: '{{ guacamole_mysql_root_password }}'
    db: test
    state: absent

- name: Update my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name: Restart MariaDB
  service: 
    name: mariadb
    state: restarted


