- name: Install firewalld
  yum:
    name: firewalld
    state: present

- name: Make sure firewalld service is running
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: open port
  firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled

- name: Redirect port 80 to 8080 with rich rule
  firewalld:
    rich_rule: rule family=ipv4 forward-port port=80 protocol=tcp to-port=8080
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

- name: reload firewall
  shell: firewall-cmd --reload



