---
# handlers file for guacamole-centos7

- name: restart tomcat
  systemd:
    name: tomcat
    state: restarted
    enabled: yes

- name: restart guacd
  systemd:
    name: guacd
    state: restarted
    enabled: yes

- name: restart mariadb
  systemd:
    name: mariadb
    state: restarted
    enabled: yes
